### ISSUE TITLE
cant send html

### ISSUE THREAD

**Issue by chelinho139** [jimrubenstein/node-mandrill#11]
Hey i am trying to send an html text but it is not displayed as html.
How do I make it?

I have my html code in this var 'htmlString'
 `mandrill('/messages/send', {
      message: {
          to: [{email: email}],
          from_email: 'info@mydomainguys.com',
          subject: "Your Beta Account is Ready - Little War Online",
          text: htmlString
          //text: "Your Account is:"+email+"\nYour password is: "+pass
      }
  },`

**Comment by akhoury** [comment]
you need to use the `html` property instead of `text`

``` javascript
mandrill('/messages/send', { 
    message: { 
      to: [{email: email}], 
      from_email: 'info@mydomainguys.com', 
      subject: "Your Beta Account is Ready - Little War Online", 

      html: htmlString, // <-- html value here
      text: textString // <-- text value here
    } 
}
```

**Comment by chelinho139** [comment]
woops, sorry for being such a rookie.

html: htmlString

fixed it! Thanks a lot for this great lib!
cheers
